- https://github.com/PennShenLab/MentalChat16K
- https://huggingface.co/datasets/ShenLab/MentalChat16K

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Interview_Data_6K.csv")

In [3]:
df.head()

,instruction,input,output
0,You are a helpful mental health counselling as...,I've been struggling with my mental health for...,I understand that you've been dealing with a s...
1,You are a helpful mental health counselling as...,I've been feeling overwhelmed with my caregivi...,"Your situation is complex, and it's important ..."
2,You are a helpful mental health counselling as...,I've been feeling constantly anxious and unabl...,I can see that you're dealing with a great dea...
3,You are a helpful mental health counselling as...,"My mom has Alzheimer's, and I've been her prim...",I'm sorry to hear that your siblings' demands ...
4,You are a helpful mental health counselling as...,"I've tried setting boundaries, but it feels li...","Your concerns are valid, and it's crucial to p..."

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6310 entries, 0 to 6309
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   instruction  6310 non-null   object
 1   input        6310 non-null   object
 2   output       6310 non-null   object
dtypes: object(3)
memory usage: 148.0+ KB

In [5]:
df['instruction'][0]

"You are a helpful mental health counselling assistant, please answer the mental health questions based on the patient's description. \nThe assistant gives helpful, comprehensive, and appropriate answers to the user's questions. "

In [6]:
df['input'][0]

"I've been struggling with my mental health for a while now, and I can't seem to find a way to cope with it. I've tried visualization, positive thinking, and even medication, but nothing seems to work. I've been feeling lost and helpless, and I don't know what to do next. My mind is a whirlwind of thoughts and emotions, and I can't seem to make sense of it all. I feel like I'm drowning in a sea of confusion, and I can't seem to find my way out."

In [7]:
df['output'][0]

"I understand that you've been dealing with a sense of confusion and chaos in your thoughts and emotions for some time now. It's been a challenging journey, and it's commendable that you've tried various approaches like visualization, positive thinking, and medication to manage your symptoms. However, it's clear that these methods haven't been effective for you. It's essential to acknowledge that mental health issues can be complex and multifaceted, and what works for one person might not work for another. Today, we're going to approach this differently. We're going to identify a specific concern related to your mental health that you'd like to work on, and we'll break it down into manageable steps. We'll define the problem as a feeling of being overwhelmed by your thoughts and emotions, and we'll set realistic goals for managing this feeling. We'll explore the root causes of this confusion, such as past traumas, current stressors, and any underlying psychological conditions. We'll also examine your thought patterns and emotional responses to these triggers, and we'll develop strategies to challenge and reframe negative thoughts. This process is called Cognitive Behavioral Therapy (CBT), and it's designed to help you face your challenges more effectively by changing the way you think and feel about them. Let's begin by discussing the specific incidents or concerns that have been contributing to your feelings of confusion and chaos. We can explore these further and come up with strategies to help you manage them."

----

In [8]:
df = pd.read_csv("Synthetic_Data_10K.csv")

In [9]:
df.head()

,instruction,input,output
0,You are a helpful mental health counselling as...,I think I might be developing a substance abus...,I'm really glad that you reached out and share...
1,You are a helpful mental health counselling as...,Parenting has become such a challenge for me. ...,I can understand how challenging parenting can...
2,You are a helpful mental health counselling as...,Intimacy has always been a struggle for me. I ...,I can understand how challenging it must be fo...
3,You are a helpful mental health counselling as...,I've been struggling with substance abuse for ...,I'm really glad that you reached out and share...
4,You are a helpful mental health counselling as...,Being a parent is overwhelming and exhausting....,Parenting can definitely be overwhelming and e...

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9774 entries, 0 to 9773
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   instruction  9774 non-null   object
 1   input        9747 non-null   object
 2   output       9774 non-null   object
dtypes: object(3)
memory usage: 229.2+ KB

In [11]:
df['instruction'][0]

"You are a helpful mental health counselling assistant, please answer the mental health questions based on the patient's description. \nThe assistant gives helpful, comprehensive, and appropriate answers to the user's questions. "

In [12]:
df['input'][0]

"I think I might be developing a substance abuse problem. Lately, I've been relying on alcohol as a way to cope with my emotions and escape from reality. It started off as occasional drinking, but now it has become a daily habit. I'm worried about the impact it's having on my physical and mental well-being, as well as my relationships and work performance."

In [13]:
df['output'][0]

"I'm really glad that you reached out and shared what you've been going through. It takes a lot of courage to acknowledge and address these concerns. I can understand how relying on alcohol as a coping mechanism might feel like an escape from reality, but it's important to remember that there are healthier ways to manage your emotions.\n\nFirstly, it's great that you're recognizing the impact this habit is having on various aspects of your life. That self-awareness is a crucial step towards making positive changes. To start addressing your substance use, you could try gradually reducing the amount of alcohol you consume each day. Setting small, achievable goals can be helpful in breaking the cycle.\n\nAdditionally, finding alternative ways to cope with your emotions can make a big difference. Engaging in activities that bring you joy or help you relax, such as exercising, practicing mindfulness or meditation, pursuing hobbies, or spending time with loved ones, can provide healthier outlets for your emotions.\n\nBuilding a support system is also essential. Reach out to friends or family members who you trust and let them know what you're going through. They may be able to offer guidance, understanding, and encouragement along your journey. If you prefer, there are also support groups available where you can connect with others who have faced similar challenges.\n\nRemember, taking care of your physical and mental well-being is vital. Prioritize getting enough sleep, eating nutritious meals, and engaging in regular exercise. These lifestyle factors can positively impact your overall health and contribute to your emotional well-being.\n\nWhile I'm here to listen and support you, it's important to consider seeking professional help if you feel overwhelmed or find it difficult to make progress on your own. A mental health professional or counselor can provide specialized guidance tailored to your specific needs and circumstances.\n\nPlease take care of yourself and don't hesitate to reach out if you need someone to talk to. You're not alone in this journey, and there is hope for positive change."