- https://github.com/ayaanzhaque/SDCNL

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("combined-set.csv")

In [3]:
df.head()

,Unnamed: 0.1,Unnamed: 0,title,selftext,author,num_comments,is_suicide,url,selftext_clean,title_clean,author_clean,selftext_length,title_length,megatext_clean
0,0,339,Need help,Hi I don't really know how to phrase this situ...,F4GG0T_,6,0,https://www.reddit.com/r/depression/comments/f...,hi really know phrase situation try life reall...,need help,f 4 gg 0,2502,9,f 4 gg 0 hi really know phrase situation try l...
1,1,1386,feeling so overwhelmed and hopeless,i have been so depressed these past couple wee...,thiccbarbie420,2,1,https://www.reddit.com/r/SuicideWatch/comments...,depressed past couple week ever since got back...,feeling overwhelmed hopeless,th icc barbie 420,843,35,th icc barbie 420 depressed past couple week e...
2,2,544,"Nothing matters anymore, getting worse",Hi..I don't know where else to go. I am devast...,mjdg25,3,0,https://www.reddit.com/r/depression/comments/f...,hi know else go devastated right feeling like ...,nothing matter anymore getting worse,mj g 25,1909,38,mj g 25 hi know else go devastated right feeli...
3,3,937,Who’s tired of hearing bullshit,"The shit like “it will get better, everyone is...",fuckxboxandgames,4,1,https://www.reddit.com/r/SuicideWatch/comments...,shit like get better everyone purpose need fin...,tired hearing bullshit,fuck xbox game,403,31,fuck xbox game shit like get better everyone p...
4,4,741,I wish I was someone else.,I wish I was prettier. I wish I didn’t feel li...,Throwawaybluestahli,1,0,https://www.reddit.com/r/depression/comments/f...,wish wa prettier wish feel like burden wish br...,wish wa someone else,throwaway bluest ahli,321,26,throwaway bluest ahli wish wa prettier wish fe...

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1895 entries, 0 to 1894
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0.1     1895 non-null   int64
 1   Unnamed: 0       1895 non-null   int64
 2   title            1895 non-null   object
 3   selftext         1895 non-null   object
 4   author           1895 non-null   object
 5   num_comments     1895 non-null   int64
 6   is_suicide       1895 non-null   int64
 7   url              1895 non-null   object
 8   selftext_clean   1894 non-null   object
 9   title_clean      1875 non-null   object
 10  author_clean     1893 non-null   object
 11  selftext_length  1895 non-null   int64
 12  title_length     1895 non-null   int64
 13  megatext_clean   1895 non-null   object
dtypes: int64(6), object(8)
memory usage: 207.4+ KB

In [4]:
df['selftext_clean'][0]  #0

'hi really know phrase situation try life really good point right never really depressed stuff 99 percent time mind clear graduate high school really excited however people family friend group ton issue wether sleep day hate ambition keep living world got problem wanna sound like gloating usually person lot people end going usually able talk people issue help long run yeah sometimes issue make really sad stuff feel sad people telling feel worthless today one best friend showed wa cutting really effected talked mostly painfully bored even know pretty logical guy go class sit hour time nothing challenging way school work ha clinically diagnosed depression ha psychiatric ward see therapist regularly couple hour since showed arm even see got two main problem right first really know help said literally thing really hang school weekend sit bed day trying make effort much need said long go highschool considering law going feel way graduate need know something help tell parent therapist help already go one talk tomorrow know second stuff like really effecting feel world unfair everyone care want everyone love feel better lately feeling depressed whenever friend need talk issue really weighing want leave people care dirt yeah anyone ha advice whatsoever please help im normally able deal feeling help friend right struggling thank'

In [5]:
df['selftext_clean'][1]  #1

'depressed past couple week ever since got back vacation normal life reality ha hit terrible im 19 havent moved yet dont really sufficient job one enough money support least car im taking online class feel stuck stupid fucking town empty alone man want someone love dude im ugly fat worthless one ever going see im worth chance one thing another worry end really fuck become miserable dont see point going im really right dont know darkness idk get hole hate hate body hate life dont think ever get better'

In [6]:
df.describe()

,Unnamed: 0.1,Unnamed: 0,num_comments,is_suicide,selftext_length,title_length
count,1895.000000,1895.000000,1895.000000,1895.000000,1895.000000,1895.000000
mean,643.800000,947.000000,4.387335,0.517150,896.292348,39.482322
std,455.446179,547.183699,12.042246,0.499838,1446.574238,30.314135
min,0.000000,0.000000,0.000000,0.000000,4.000000,2.000000
25%,236.500000,473.500000,1.000000,0.000000,237.500000,20.000000
50%,568.000000,947.000000,2.000000,1.000000,516.000000,31.000000
75%,1041.500000,1420.500000,4.000000,1.000000,1074.500000,50.000000
max,1515.000000,1894.000000,260.000000,1.000000,24586.000000,266.000000