- https://www.kaggle.com/datasets/mexwell/ai-driven-mental-health-literacy
- https://psycharchives.org/en/item/2c9edde4-bc2f-44ca-b5bd-6e8438681e1f

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Data - AI Driven MH Literacy.csv")

In [3]:
df.head()

,Age,Gender,Educational.Qualification,GPT_Use,pre.MHL_KMHP,pre.MHL_EBS,pre.MHL_FASHSB,pre.MHL_SHS,pre.MHL_Total,pre.MHSAS,...,post.SPANE_P,post.SPANE_N,post.SPANE_B,post.FLOUSC,GPT_Rating,Prompts_Rating,Intervention_Rating,MHL_Rating,GPT_MHL,GPT_Flaw
0,19,Female,Bcom,Occasionally (once or twice),28,12,13,19,72,4.777778,...,16,21,-5,32,Good,Excellent,Good,Yes,Maybe,No
1,20,Male,Bcom computer application,Occasionally (once or twice),29,11,14,19,73,6.111111,...,15,20,-5,30,Excellent,Excellent,Excellent,Yes,Yes,No
2,19,Female,Pursuing a Bachelor's degree (BA/ BSc/ BTech),Always (daily),25,12,13,17,67,6.444444,...,21,16,5,40,Good,Good,Excellent,Yes,Yes,No
3,20,Female,Pursuing a Bachelor's degree (BA/ BSc/ BTech),Never,24,11,11,18,64,4.555556,...,26,19,7,48,Good,Excellent,Good,Yes,Maybe,Maybe
4,19,Female,Pursuing a Bachelor's degree (BA/ BSc/ BTech),Never,26,9,13,17,65,5.222222,...,15,24,-9,42,Excellent,Good,Good,Yes,Maybe,Maybe

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 34 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Age                        51 non-null     int64
 1   Gender                     51 non-null     object
 2   Educational.Qualification  51 non-null     object
 3   GPT_Use                    51 non-null     object
 4   pre.MHL_KMHP               51 non-null     int64
 5   pre.MHL_EBS                51 non-null     int64
 6   pre.MHL_FASHSB             51 non-null     int64
 7   pre.MHL_SHS                51 non-null     int64
 8   pre.MHL_Total              51 non-null     int64
 9   pre.MHSAS                  51 non-null     float64
 10  pre.STIG                   51 non-null     int64
 11  pre.MHSES                  51 non-null     int64
 12  pre.SPANE_P                51 non-null     int64
 13  pre.SPANE_N                51 non-null     int64
 14  pre.SPANE_B                51 non-null     int64
 15  pre.FLOUSC                 51 non-null     int64
 16  post.MHL_KMHP              51 non-null     int64
 17  post.MHL_EBS               51 non-null     int64
 18  post.MHL_FASHSB            51 non-null     int64
 19  post.MHL_SHS               51 non-null     int64
 20  post.MHL_Total             51 non-null     int64
 21  post.MHSAS                 51 non-null     float64
 22  post.STIG                  51 non-null     int64
 23  post.MHSES                 51 non-null     int64
 24  post.SPANE_P               51 non-null     int64
 25  post.SPANE_N               51 non-null     int64
 26  post.SPANE_B               51 non-null     int64
 27  post.FLOUSC                51 non-null     int64
 28  GPT_Rating                 51 non-null     object
 29  Prompts_Rating             51 non-null     object
 30  Intervention_Rating        51 non-null     object
 31  MHL_Rating                 51 non-null     object
 32  GPT_MHL                    51 non-null     object
 33  GPT_Flaw                   51 non-null     object
dtypes: float64(2), int64(23), object(9)
memory usage: 13.7+ KB

In [5]:
df['Educational.Qualification'].value_counts()

Educational.Qualification
Pursuing a Bachelor's degree (BA/ BSc/ BTech)     30
Completed a Master's course (MA/ MSc/ MTech)       6
Completed a Bachelor's course (BA/ BSc/ BTech)     3
Bcom                                               2
Bcom computer application                          1
B.com computer application                         1
pursuing a Bachelor's Degree( B.Com CA)            1
Pursuing a bachelors degree (Bcom)                 1
Pursuing bcom computer application                 1
Pursuing a Ph.D.                                   1
BSc Psychology                                     1
BCOM                                               1
plus two                                           1
Pursuing a bachelor's degree(b. Com)               1
Name: count, dtype: int64

In [6]:
df['GPT_Use'].value_counts()

GPT_Use
Never                           25
Occasionally (once or twice)    13
Sometimes (once a week)          8
Always (daily)                   5
Name: count, dtype: int64

In [7]:
df.describe()

,Age,pre.MHL_KMHP,pre.MHL_EBS,pre.MHL_FASHSB,pre.MHL_SHS,pre.MHL_Total,pre.MHSAS,pre.STIG,pre.MHSES,pre.SPANE_P,...,post.MHL_FASHSB,post.MHL_SHS,post.MHL_Total,post.MHSAS,post.STIG,post.MHSES,post.SPANE_P,post.SPANE_N,post.SPANE_B,post.FLOUSC
count,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,...,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000
mean,19.823529,24.137255,12.411765,12.098039,16.529412,65.176471,5.808279,16.725490,35.392157,19.372549,...,12.980392,17.509804,69.019608,6.019608,14.549020,42.235294,19.686275,18.647059,1.039216,40.803922
std,1.807826,3.364637,1.675428,1.910549,1.724563,5.931967,1.045408,5.862008,10.579373,3.918983,...,2.024749,1.911780,8.871280,1.122102,8.424521,12.415455,3.685052,2.917694,5.858194,7.340353
min,18.000000,18.000000,9.000000,8.000000,11.000000,53.000000,3.555556,0.000000,15.000000,12.000000,...,9.000000,15.000000,56.000000,4.000000,1.000000,14.000000,13.000000,12.000000,-10.000000,26.000000
25%,19.000000,22.000000,12.000000,11.000000,15.000000,62.000000,5.111111,13.500000,27.500000,17.000000,...,11.000000,16.000000,61.000000,5.388889,6.000000,38.000000,17.000000,17.000000,-3.000000,36.000000
50%,19.000000,24.000000,12.000000,12.000000,17.000000,65.000000,6.111111,17.000000,36.000000,19.000000,...,13.000000,17.000000,70.000000,6.333333,14.000000,45.000000,20.000000,19.000000,1.000000,42.000000
75%,20.000000,26.000000,13.500000,13.000000,17.500000,68.500000,6.666667,22.000000,41.000000,22.500000,...,15.000000,20.000000,78.000000,7.000000,21.500000,48.000000,21.000000,21.000000,4.500000,46.000000
max,25.000000,30.000000,15.000000,15.000000,20.000000,77.000000,7.000000,27.000000,55.000000,30.000000,...,15.000000,20.000000,80.000000,7.000000,27.000000,60.000000,30.000000,24.000000,14.000000,56.000000