- https://huggingface.co/datasets/jastorj/MHQA
- https://aikosh.indiaai.gov.in/home/datasets/details/bharatgen_mhqa_dataset.html

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("mhqa.csv")

In [3]:
df.head()

,id,topic,type,question,option1,option2,option3,option4,correct_option,correct_option_number
0,28615767,Depression,Diagnostic,Which subgroup reported lower perceived social...,Recurrent depressive disorder patients,Anxiety disorder patients,Healthy individuals,First-episode depression patients,Recurrent depressive disorder patients,1
1,17291595,Obsessive/Compulsive Disorders,Factoid,Which group of patients exhibited lower levels...,Healthy controls,Those with social anxiety disorder,Schizophrenic patients without obsessive-compu...,Patients with obsessive-compulsive disorder,Patients with obsessive-compulsive disorder,4
2,38514191,Obsessive/Compulsive Disorders,Prognostic,How does the overexpression of the Slc1a1 gene...,Decreases hyperactivity,Diminishes nerve response,Reduces locomotion,Increases stereotypy,Increases stereotypy,4
3,12787851,Obsessive/Compulsive Disorders,Preventive,What treatment was shown to gradually decrease...,Behavioral modification training,Cognitive-behavioral therapy,Risperidone,Fluoxetine,Fluoxetine,4
4,24480417,Obsessive/Compulsive Disorders,Preventive,How does maternal obsessive-compulsive disorde...,By reducing maternal anxiety symptoms,By decreasing fetal TNF-Î± levels,By improving maternal mental health,By increasing fetal neuroinflammation,By increasing fetal neuroinflammation,4

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2475 entries, 0 to 2474
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     2475 non-null   int64
 1   topic                  2475 non-null   str
 2   type                   2475 non-null   str
 3   question               2475 non-null   str
 4   option1                2475 non-null   str
 5   option2                2475 non-null   str
 6   option3                2475 non-null   str
 7   option4                2475 non-null   str
 8   correct_option         2475 non-null   str
 9   correct_option_number  2475 non-null   int64
dtypes: int64(2), str(8)
memory usage: 193.5 KB

In [5]:
df['type'].value_counts()

type
Diagnostic    879
Preventive    714
Prognostic    558
Factoid       324
Name: count, dtype: int64

In [6]:
df['topic'].value_counts()

topic
Obsessive/Compulsive Disorders    637
Depression                        617
Trauma                            617
Anxiety                           604
Name: count, dtype: int64

In [7]:
df

,id,topic,type,question,option1,option2,option3,option4,correct_option,correct_option_number
0,28615767,Depression,Diagnostic,Which subgroup reported lower perceived social...,Recurrent depressive disorder patients,Anxiety disorder patients,Healthy individuals,First-episode depression patients,Recurrent depressive disorder patients,1
1,17291595,Obsessive/Compulsive Disorders,Factoid,Which group of patients exhibited lower levels...,Healthy controls,Those with social anxiety disorder,Schizophrenic patients without obsessive-compu...,Patients with obsessive-compulsive disorder,Patients with obsessive-compulsive disorder,4
2,38514191,Obsessive/Compulsive Disorders,Prognostic,How does the overexpression of the Slc1a1 gene...,Decreases hyperactivity,Diminishes nerve response,Reduces locomotion,Increases stereotypy,Increases stereotypy,4
3,12787851,Obsessive/Compulsive Disorders,Preventive,What treatment was shown to gradually decrease...,Behavioral modification training,Cognitive-behavioral therapy,Risperidone,Fluoxetine,Fluoxetine,4
4,24480417,Obsessive/Compulsive Disorders,Preventive,How does maternal obsessive-compulsive disorde...,By reducing maternal anxiety symptoms,By decreasing fetal TNF-Î± levels,By improving maternal mental health,By increasing fetal neuroinflammation,By increasing fetal neuroinflammation,4
...,...,...,...,...,...,...,...,...,...,...
2470,35666583,Obsessive/Compulsive Disorders,Diagnostic,What factor is positively correlated with comp...,Age,Gender,Body image dissatisfaction,Type of exercise,Body image dissatisfaction,3
2471,17174859,Obsessive/Compulsive Disorders,Diagnostic,Which demographic was more likely to have clin...,Younger participants,Male participants,Older participants,Integrated participants,Younger participants,1
2472,26843373,Obsessive/Compulsive Disorders,Preventive,What innovative treatment method is suggested ...,Mindfulness training,Cognitive-behavioral therapy,Electroconvulsive therapy,Transcranial magnetic stimulation,Transcranial magnetic stimulation,4
2473,28615767,Depression,Diagnostic,Which subgroup reported lower perceived social...,Recurrent depressive disorder patients,Anxiety disorder patients,Healthy individuals,First-episode depression patients,Recurrent depressive disorder patients,1
2474,33270336,Trauma,Preventive,What factors should be considered to minimize ...,Understanding patient experiences,Strict adherence to medical guidelines,Implementation of medication protocols,Regular staff meetings,Understanding patient experiences,1